config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  resources :items, :only => [:index, :show]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root to: 'visitors#index'
  resources :cart, :only => [:index, :update, :destroy]
  patch '/cart', to: 'cart#update', as: 'update_cart'
  patch '/cart_remove', to: 'cart#delete', as: 'remove_item'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  include Payola::Sellable
end

app/models/item.rb
class Item < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  #attr_accessible :image, :image_cache, :remove_image
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:cart) }
  end
end

app/controllers/cart_controller.rb
# Cart Controller, which accumulates item references for the current user
class CartController < ApplicationController
  def index
    quantity = Hash.new(0)
    total_price = 0
    current_user.cart.each do |i|
      item = Item.find(i)
      quantity[i] += 1
      total_price += item.price
    end
    c = Cart.new
    c.price = (total_price * 100).to_i
    c.quantity = quantity
    c.name = "#{current_user.name}'s Cart"
    c.permalink = SecureRandom.uuid
    c.save
    @cart = Cart.find(c.id)
  end

  def update
    @item = Item.find(params[:item_id])
    current_user.cart << @item.id
    current_user.save
    redirect_to cart_index_path, notice: 'Your cart was successfully updated.'
  end

  def delete
    @item = Item.find(params[:item_id])
    i = @item.id.to_s
    current_user.cart.delete_at(current_user.cart.find_index(i))
    current_user.save
    redirect_to cart_index_path, notice: 'Your item has been successfully removed.'
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    @cart.save
    current_user.cart = []
    current_user.save
    redirect_to cart_index_path, notice: 'Your cart is empty.'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @items = Item.all
  end

  def show

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :short_description, :description, :image, :price)
    end
end

app/controllers/registrations_controller.rb
# Override for the devise registration controller in order to save the user's actual name
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cart/index.html.erb
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="quantity">Update</td>
						</tr>
					</thead>
					<tbody>
							<% if @cart.quantity != nil %>
								<% @cart.quantity.each do |i, number| %>
								<tr>
									<% item = Item.find(i) %>
									<td class="cart_product">
											<%unless item.image.blank? %>
												<%= image_tag(item.image.thumb) %>
											<%end %>
									</td>
									<td class="cart_description">
										<%= item.name %>
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td class="cart_price">
										<p><%= number_to_currency(item.price) %></p>
									</td>
									<td class="cart_quantity">
									<%= number %>
									</td>

									<td class="cart_adjust">
										<%= form_tag("/cart", action: update_cart_path(item), method: "patch") do %>
											<input name="item_id" type="hidden" value=<%= item.id %> />
											<button type="submit" class="btn btn-default"><i class="fa fa-plus"></i></button>
										<% end %>
										<%= form_tag("/cart_remove", action: remove_item_path(item), method: "patch") do %>
											<input name="item_id" type="hidden" value=<%= item.id %> />
											<button type="submit" class="btn btn-default"><i class="fa fa-minus"></i></button>
										<% end %>
									</td>
								</tr>
								<% end %>

							<% else %>
							<%= puts "Your cart is empty." %>
							<% end %>

					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="row">
					<div class="col-sm-6">
						<div class="total_area">
						<%= link_to 'Clear Cart', cart_path(@cart), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default update" %>
							<ul>
								<li>Cart Subtotal <span><%= number_to_currency(@cart.price.fdiv(100)) %></span></li>
								<li>Tax <span>Free</span></li>
								<li>Shipping Cost <span>Free</span></li>
								<li>Total <span><%= number_to_currency(@cart.price.fdiv(100)) %></span></li>
							</ul>

							<a><%= render 'payola/transactions/checkout',
												 sellable: @cart, button_class: "btn btn-default check_out" %></a>

					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->

app/views/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 padding-right">
			<div class="features_items"><!--featured_items-->
				<h2 class="title text-center">Listing Items</h2>
					<% @items.each do |item| %>
						<div class="col-sm-3">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
											<%unless item.image.blank?%>
												<p><%= image_tag(item.image.url) %></p>
											<%end%>
										<h4><%= link_to item.name, item %></h4>
										<p><%= item.short_description %></p>
										<h2><%= number_to_currency(item.price) %></h2>
									</div>
								</div>
							</div>
						</div>
					<% end  %>

			</div>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="row">
		<h1><%= @item.name %></h1>
		<h4><%= @item.description %></h4>

		<% unless @item.image.blank?  %>
			<%= image_tag(@item.image.url) %>
		<%end  %>

		<h2><%= number_to_currency(@item.price) %></h2>

		<%= form_tag("/cart", action: update_cart_path(@item), method: "patch") do %>
				<input name="item_id" type="hidden" value=<%=@item.id  %> />
				<button type="submit" class="btn btn-submit add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a></button>
		<% end %>

		<%= link_to 'Back', items_path, class: "btn btn-default" %>
    <br>
    <br>
	</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="header_top"><!--header_top-->
  <div class="container">
    <div class="row">
    </div>
  </div>
</div><!--/header_top-->

<div class="header-middle"><!--header-middle-->
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="logo pull-left">
          <a href="/"><%= image_tag "logo_full.png" %></a>
        </div>
      </div>
      <div class="col-sm-8">
        <div class="shop-menu pull-right">
          <ul class="nav navbar-nav">
            <%= render 'layouts/navigation_links' %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div><!--/header-middle-->

<div class="header-bottom"><!--header-bottom-->
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="mainmenu pull-left">
          <ul class="nav navbar-nav collapse navbar-collapse">
            <li><a href="/" class="active">Home</a></li>
            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
              <ul role="menu" class="sub-menu">
                <li><%= link_to 'Collars & Leashes', items_path %></li>
                <li><%= link_to 'Fashion', items_path %></li>
                <li><%= link_to 'Dishes', items_path %></li>
                <li><%= link_to 'Litter and Litter Boxes', items_path %></li>
                <li><%= link_to 'Furniture', items_path %></li>
              </ul>
            </li>
            <li><%= link_to 'Contact Us', page_path('about') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div><!--/header-bottom-->


<!-- <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
<li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
 -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to page_path('about') do %>
  		<i class="fa fa-info-circle"></i>
  		About
  		<% end %>
  </li>
<% if user_signed_in? %>
  <li><%= link_to edit_user_registration_path do %>
  		<i class="fa fa-user"></i>
  		Account
  		<% end %>
  </li>
	<!-- replace with proper path when built -->
	<li><%= link_to cart_index_path do %>
  		<i class="fa fa-shopping-cart"></i>
  		Cart(<%=current_user.cart.length  %>)
  		<% end %>
  </li>
	<li><%= link_to destroy_user_session_path, :method=>'delete' do %>
  		<i class="fa fa-sign-out"></i>
  		Sign Out
  		<% end %>
  </li>
<% else %>
	<li><%= link_to new_user_session_path do %>
  		<i class="fa fa-lock"></i>
  		Sign In
  		<% end %>
  </li>
  <li><%= link_to new_user_registration_path do %>
  		<i class="fa fa-plus-square"></i>
  		Sign Up
  		<% end %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Glamazon" %>">
    <meta name="author" content="Michael Nash & Kelly Bristol">
    <title><%= content_for?(:title) ? yield(:title) : "Glamazon" %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">
    <link href="assets/stylesheets/prettyPhoto.css" rel="stylesheet">
    <link href="assets/stylesheets/price-range.css" rel="stylesheet">
    <link href="assets/stylesheets/animate.css" rel="stylesheet">
    <link href="assets/stylesheets/main.css" rel="stylesheet">
    <link href="assets/stylesheets/responsive.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head><!--/head-->

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <%= render 'layouts/messages' %>
    <section>
      <%= yield %>
    </section>


    <footer id="footer"><!--Footer-->
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <div class="companyinfo">
              <h2>Glamazon</h2>
                <p>Bringing you the finest accessories for your distinguished cat.</p>
              </div>
            </div>

            <div class="col-sm-2">
              <div class="address">
                <%= image_tag "map.png" %>
                <p>260 1st Ave S, #300 St. Petersburg, FL 33701</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="footer-bottom">
        <div class="container">
          <div class="row">
            <p class="pull-left">Copyright © <%= Date.today.year %> GLAMAZON PET PRODUCTS, Inc. All rights reserved.</p>
            <p class="pull-right">Designed by <span><a target="_blank" href="http://www.theironyard.com">Michael Nash & Kelly Bristol</a></span></p>
          </div>
        </div>
      </div>
    </footer><!--/Footer-->

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/price-range.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>

<h6>
	Created by <%= link_to('Michael Nash', 'https://github.com/utumno86')  %>  and <%= link_to('Kelly Bristol', 'https://github.com/cateia97') %>
</h6>
<h6>
	For The Iron Yard St.Petersburg/Tampa 3rd Ruby on Rails Cohort Summer 2015
</h6>

<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<!-- index page with feature carousel -->

<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<a href="/"><%= image_tag "logo_full.png" %></a>
									<h2>Where Posh Cats Shop</h2>
									<p>Check out the hottest fashions from Meowant Park's runways! </p>
									<%= link_to 'Get It Now', items_path, class: "btn btn-default get" %>
								</div>
								<div class="col-sm-6">
									<%= image_tag("cat_cleopatra.jpg", :class => "cat img-responsive") %>
									<!-- <img src="images/home/pricing.png"  class="pricing" alt="" /> -->
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<a href="/"><%= image_tag "logo_full.png" %></a>
									<h2>Where Posh Cats Shop</h2>
									<p>Halloween is coming! Kitty is sure to get only treats in our new luchador masks! </p>
									<%= link_to 'Get It Now', items_path, class: "btn btn-default get" %>
								</div>
								<div class="col-sm-6">
									<%= image_tag("cat_luchas.jpg", :class => "cat img-responsive") %>
									<!-- <img src="images/home/pricing.png"  class="pricing" alt="" /> -->
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<a href="/"><%= image_tag "logo_full.png" %></a>
									<h2>Where Posh Cats Shop</h2>
									<p>You asked, and we delivered! Rainbow gLitter available now! </p>
									<%= link_to 'Get It Now', items_path, class: "btn btn-default get" %>
								</div>
								<div class="col-sm-6">
									<%= image_tag("bling_litter.jpg", :class => "cat img-responsive") %>
									<!-- <img src="images/home/pricing.png" class="pricing" alt="" /> -->
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->

	<section><!--/sidebar and feature-->
		<div class="container">
			<div class="row">

				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
							<div class="panel-group category-products" id="accordian"><!--category-productsr-->
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a data-toggle="collapse" data-parent="#accordian" href="#collars">
												<span class="badge pull-right"><i class="fa fa-plus"></i></span>
												Collars & Leashes
											</a>
										</h4>
									</div>
									<div id="collars" class="panel-collapse collapse">
										<div class="panel-body">
											<ul>
												<li><a href="items">Swarovski </a></li>
												<li><a href="items">Coach </a></li>
												<li><a href="items">Chanel </a></li>
												<li><a href="items">Puma</a></li>
											</ul>
										</div>
									</div>
								</div>

								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a data-toggle="collapse" data-parent="#accordian" href="#fashion">
												<span class="badge pull-right"><i class="fa fa-plus"></i></span>
												Fashion
											</a>
										</h4>
									</div>
									<div id="fashion" class="panel-collapse collapse">
										<div class="panel-body">
											<ul>
												<li><a href="items">Fendi</a></li>
												<li><a href="items">Guess</a></li>
											</ul>
										</div>
									</div>
								</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="items">
											Feeding Accessories
										</a>
									</h4>
								</div>
								<div id="dishes" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="items">Single Bowl</a></li>
											<li><a href="items">Double Bowls</a></li>
											<li><a href="items">Timed Feeders</a></li>
											<li><a href="items">Water Fountains</a></li>
											<li><a href="items">Fresh Greens</a></li>
										</ul>
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="items">Litter</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="items">Litter Boxes</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="items">Food</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="items">Furniture</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="items">Toys</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					</div><!--/left-sidebar-->
				</div><!--/col-sm-3-->

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--featured_items-->
						<h2 class="title text-center">Featured Items</h2>

					<% 6.times do %>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<%= image_tag "bling_collars.jpg" %>
										<h2>$99.99</h2>
										<p>Blinged Cat Collar</p>
										<a href="items" class="btn btn-default add-to-cart">See Products</a>
									</div>
								</div>
							</div>
						</div>
					<% end %>

				</div><!--/col-sm-9-->
			</div><!--/row-->
		</div><!--/container-->
	</section><!--/sidebar and feature-->